// <auto-generated />
namespace FootballTeamManager.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20170923_Dodanie_LP_do_Player : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20170923_Dodanie_LP_do_Player));
        
        string IMigrationMetadata.Id
        {
            get { return "201709231147309_20170923_Dodanie_LP_do_Player"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
